name: Continuous Integration
on: push

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: npm install
              run: npm i

            - name: Lint code
              run: npm run lint
