name: PR Coverage Report
on: pull_request

jobs:
    coverage:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            pull-requests: write
            checks: write

        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
